#pragma once

URHO3D_EVENT(E_PLAYER_CHECKBOX_PRESSED, PLAYER_CHECKBOX_PRESSED)
{
	URHO3D_PARAM(P_TEAM, PlayerTeam); // int 
	URHO3D_PARAM(P_PLAYER_NUMBER, PlayerNumber); // int 
	URHO3D_PARAM(P_VALUE, Value);  // bool
}

URHO3D_EVENT(E_SIMULATION_SLIDER_CHANGE, SIMULATION_SLIDER_CHANGE)
{
	URHO3D_PARAM(P_VALUE, Value);  // float
}

URHO3D_EVENT(E_ENERGY_VALUE_CHANGE, ENERGY_VALUE_CHANGE)
{
	URHO3D_PARAM(P_TEAM, PlayerTeam); // int 
	URHO3D_PARAM(P_VALUE, Value);  // float
}

URHO3D_EVENT(E_STOP_SIMULATION, STOP_SIMULATION)
{

}

URHO3D_EVENT(E_INTRO_SIMULATION, INTRO_SIMULATION)
{

}

URHO3D_EVENT(E_FIRST_KICK, FIRST_KICK)
{

}

URHO3D_EVENT(E_RESTART_SIMULATION, RESTART_SIMULATION)
{

}

URHO3D_EVENT(E_COMMENT, COMMENT)
{
    URHO3D_PARAM(P_COMMENT, COMMENT); // int
}